apiVersion: apps/v1
kind: Deployment
metadata:
  name: resta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resta
  template:
    metadata:
      labels:
        app: resta
    spec:
      containers:
      - name: resta
        image: servicio-resta:latest
        ports:
        - containerPort: 3000 # Reemplaza con el puerto que usa tu contenedor de resta
