apiVersion: v1
kind: Service
metadata:
  name: suma-service
spec:
  selector:
    app: suma
  ports:
    - protocol: TCP
      port: 80 # Puerto a través del cual se accederá al servicio
      targetPort: 3000 # Puerto en el contenedor donde el servicio está escuchando
